trigger: none   # No automatic triggers, pipeline will be run manually

pr: none        # No PR trigger, pipeline will not run on PRs automatically

# Define parameters for branch selection
parameters:
  - name: branchSelector
    displayName: "Select branch"
    type: string
    default: dev
    values:
      - dev
      - uat

stages:
  - stage: SelectBranch
    displayName: "Branch Selection"
    jobs:
      - job: EchoBranch
        displayName: "Echo Selected Branch Name"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Running pipeline on the branch: $(parameters.branchSelector)"
            displayName: "Echo the branch name"
