trigger: none   # No automatic triggers, pipeline will be run manually

pr: none        # No PR trigger, pipeline will not run on PRs automatically

# Define parameters for branch selection
parameters:
  - name: branchSelector
    displayName: "Select branch"
    type: string
    default: dev
    values:
      - dev
      - uat
      - master

stages:
  - stage: SelectBranch
    displayName: "Branch Selection"
    jobs:
      - job: EchoBranch
        displayName: "Echo Selected Branch Name"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Task to echo the selected branch name
          - script: |
              echo "Running pipeline on the branch: ${{ parameters.branchSelector }}"
            displayName: "Echo the branch name"

  # SIT Stage - Runs only when the selected branch is 'master'
  - stage: SIT
    displayName: "SIT Stage"
    condition: and(succeeded(), eq('${{ parameters.branchSelector }}', 'master'))
    jobs:
      - job: SITJob
        displayName: "SIT Job"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Running SIT tests..."
            displayName: "Echo SIT Step 1"
          - script: |
              echo "Step 2: Validating SIT environment..."
            displayName: "SIT Validation Step"
          - script: |
              echo "Step 3: Deploying to SIT environment..."
            displayName: "SIT Deployment Step"
          - script: |
              echo "Step 4: Running SIT cleanup..."
            displayName: "SIT Cleanup Step"

  # UAT Stage - Runs only when the selected branch is 'master'
  - stage: UAT
    displayName: "UAT Stage"
    condition: and(succeeded(), eq('${{ parameters.branchSelector }}', 'master'))
    jobs:
      - job: UATJob
        displayName: "UAT Job"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Running UAT tests..."
            displayName: "Echo UAT Step 1"
          - script: |
              echo "Step 2: Validating UAT environment..."
            displayName: "UAT Validation Step"
          - script: |
              echo "Step 3: Deploying to UAT environment..."
            displayName: "UAT Deployment Step"
          - script: |
              echo "Step 4: Running UAT cleanup..."
            displayName: "UAT Cleanup Step"
