trigger:
  branches:
    include:
      - master
      - production

pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SIT_UAT
    displayName: 'Deploy to SIT and UAT Workspaces'
    condition: eq(variables['Build.SourceBranchName'], 'master')
    jobs:
      - job: CopyToSIT
        displayName: 'Copy Files to SIT Databricks Workspace'
        steps:
          - script: |
              echo "Copying files to SIT workspace: $(SIT_WORKSPACE)"
              # Add the command to copy files to the SIT Databricks workspace
              echo "Files copied to SIT Databricks Workspace"
        variables:
          SIT_WORKSPACE: 'sit-databricks-workspace-url'

      - job: CopyToUAT
        displayName: 'Copy Files to UAT Databricks Workspace'
        dependsOn: CopyToSIT
        steps:
          - script: |
              echo "Copying files to UAT workspace: $(UAT_WORKSPACE)"
              # Add the command to copy files to the UAT Databricks workspace
              echo "Files copied to UAT Databricks Workspace"
        variables:
          UAT_WORKSPACE: 'uat-databricks-workspace-url'

  - stage: Production
    displayName: 'Deploy to Production Workspace'
    condition: eq(variables['Build.SourceBranchName'], 'production')
    jobs:
      - job: CopyToProd
        displayName: 'Copy Files to Prod Databricks Workspace'
        steps:
          - script: |
              echo "Copying files to Production workspace: $(PROD_WORKSPACE)"
              # Add the command to copy files to the Production Databricks workspace
              echo "Files copied to Prod Databricks Workspace"
        variables:
          PROD_WORKSPACE: 'prod-databricks-workspace-url'
