trigger:
  branches:
    include:
      - master
      - production

pr: none

pool:
  vmImage: 'ubuntu-latest'  # Change this if you're using a Windows agent

stages:
  - stage: SIT_UAT
    displayName: 'Deploy to SIT and UAT Workspaces'
    condition: eq(variables['Build.SourceBranchName'], 'master')
    jobs:
      - job: CopyToSIT
        displayName: 'Copy Files to SIT Databricks Workspace'
        steps:
          - script: |
              echo "This is a test message for SIT."
              echo "Workspace Name: ${{ variables.SIT_WORKSPACE }}"
            displayName: 'Echo Workspace Name'
          - script: |
              echo "Current PATH: $PATH"
              # Replace this with the command to copy files, if using Databricks CLI
              # databricks fs cp /local/path ${{ variables.SIT_WORKSPACE }} --recursive
            displayName: 'Check Tools Availability'
        variables:
          SIT_WORKSPACE: 'sit-databricks-workspace-url'

      - job: CopyToUAT
        displayName: 'Copy Files to UAT Databricks Workspace'
        dependsOn: CopyToSIT
        steps:
          - script: |
              echo "This is a test message for UAT."
              echo "Workspace Name: ${{ variables.UAT_WORKSPACE }}"
            displayName: 'Echo Workspace Name'
          - script: |
              echo "Current PATH: $PATH"
              # databricks fs cp /local/path ${{ variables.UAT_WORKSPACE }} --recursive
            displayName: 'Check Tools Availability'
        variables:
          UAT_WORKSPACE: 'uat-databricks-workspace-url'

  - stage: Production
    displayName: 'Deploy to Production Workspace'
    condition: eq(variables['Build.SourceBranchName'], 'production')
    jobs:
      - job: CopyToProd
        displayName: 'Copy Files to Prod Databricks Workspace'
        steps:
          - script: |
              echo "This is a test message for Production."
              echo "Workspace Name: ${{ variables.PROD_WORKSPACE }}"
            displayName: 'Echo Workspace Name'
          - script: |
              echo "Current PATH: $PATH"
              # databricks fs cp /local/path ${{ variables.PROD_WORKSPACE }} --recursive
            displayName: 'Check Tools Availability'
        variables:
          PROD_WORKSPACE: 'prod-databricks-workspace-url'
